from os.path import expanduser
from pprint import pprint
from pronoteapijsonparser import PronoteApiJsonParser
from timetableparser import TimeTableParser
from timetablewriter import TimeTableWriter

jsonparser = PronoteApiJsonParser(True)
writer = TimeTableWriter(True)
# Read result.json generated by pronote-fetch
name,weekA = jsonparser.parse(expanduser("~/GIT/Pdf2TimeTable/Pdf2TimeTable/test/week_a.json"))
name,weekB = jsonparser.parse(expanduser("~/GIT/Pdf2TimeTable/Pdf2TimeTable/test/week_b.json"))
prepared_data = {
        'Week A':weekA,
        'Week B':weekB}
pprint(prepared_data)
writer.write_prepared_data_to_excel(name, prepared_data, "test/output.xlsx")
print("output file is `test/output.xlsx`")
