from os.path import expanduser
from pprint import pprint
from pronoteapijsonparser import PronoteApiJsonParser
from timetableparser import TimeTableParser
from timetablewriter import TimeTableWriter

jsonparser = PronoteApiJsonParser(True)
writer = TimeTableWriter(True)
# Read result.json generated by pronote-fetch
name,weekA = jsonparser.parse(expanduser("~/Documents/Python/test/result.json"))
prepared_data = {
        'Week A':weekA,
        'Week B':weekA}
writer.write_prepared_data_to_excel(name, prepared_data, "test/output.xlsx")
print("output file is `test/output.xlsx`")
